      --build=never `
      --profile=dependencies\conan_profiles\msvc-x64 `
      -s "&:build_type=RelWithDebInfo" `
      -c tools.cmake.cmaketoolchain:generator=Ninja `
      -c tools.microsoft.msbuild:vs_version=17 `
      -o "&:target_pre_windows10=True"

    if ($LASTEXITCODE -ne 0) {
      throw "Conan install failed"
    }

    call conan-msvc\conanrun.bat

    cmake -S . `
      -B build `
      -G Ninja `
      -DCMAKE_TOOLCHAIN_FILE="$repo\conan-msvc\conan_toolchain.cmake" `
      -DCMAKE_BUILD_TYPE=RelWithDebInfo `
      -DENABLE_CCACHE=OFF `
      -DENABLE_TEST=OFF `
      -DENABLE_PCH=OFF

    if ($LASTEXITCODE -ne 0) {
      throw "CMake configure failed"
    }

    cmake --build build --parallel 2

    if ($LASTEXITCODE -ne 0) {
      throw "VCMI build failed"
    }
  displayName: Configure and build VCMI

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/build'
    artifact: 'Nullkiller2-v0.12-alpha1-build'
  displayName: Publish Nullkiller2 build artifact
